apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: simple-vue-app
  version: 0.1.0
  repo: https://ultrajeff.github.io/helm-charts
  namespace: user1-bgd
  valuesFile: values.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/labels/testkey
      value: testvalue
  target:
    group: apps
    kind: Deployment
    name: simple-vue-kustomize
    version: v1
